-- MySQL Script generated by MySQL Workbench
-- Sun May 11 15:02:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taller_jpa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `taller_jpa` ;

-- -----------------------------------------------------
-- Schema taller_jpa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taller_jpa` DEFAULT CHARACTER SET utf8 ;
USE `taller_jpa` ;

-- -----------------------------------------------------
-- Table `taller_jpa`.`tipo_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`tipo_empleado` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`tipo_empleado` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`direccion` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`direccion` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `colonia` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`empleado` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`empleado` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `correo` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NOT NULL,
  `rfc` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NOT NULL,
  `fecha_baja` DATETIME NULL,
  `isActivo` TINYINT NOT NULL DEFAULT 1,
  `D_id` BIGINT NOT NULL,
  `TE_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_tipo_empleado1_idx` (`TE_id` ASC) VISIBLE,
  INDEX `fk_empleado_direccion1_idx` (`D_id` ASC) VISIBLE,
  UNIQUE INDEX `direccion_id_UNIQUE` (`D_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_tipo_empleado1`
    FOREIGN KEY (`TE_id`)
    REFERENCES `taller_jpa`.`tipo_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_direccion1`
    FOREIGN KEY (`D_id`)
    REFERENCES `taller_jpa`.`direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`usuario` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  `E_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_empleado1_idx` (`E_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empleado1`
    FOREIGN KEY (`E_id`)
    REFERENCES `taller_jpa`.`empleado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(10) NULL,
  `direccion` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`refaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`refaccion` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`refaccion` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `categoria` ENUM('pantalla', 'inventario') NULL,
  `stock` INT NULL,
  `precio_venta` FLOAT NULL,
  `precio_compra` FLOAT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_refaccion_proveedor_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_refaccion_proveedor`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `taller_jpa`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`pedidos` (
  `id`  NOT NULL,
  `fecha_pedido` DATETIME NULL,
  `estado` ENUM('pendiente', 'completado') NULL,
  `observaciones` VARCHAR(45) NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_proveedor1_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `taller_jpa`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`detalles_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`detalles_pedido` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`detalles_pedido` (
  `id` INT NOT NULL,
  `cantidad` INT NULL,
  `pedidos_id`  NOT NULL,
  `refaccion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalles_pedido_pedidos1_idx` (`pedidos_id` ASC) VISIBLE,
  INDEX `fk_detalles_pedido_refaccion1_idx` (`refaccion_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalles_pedido_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `taller_jpa`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_pedido_refaccion1`
    FOREIGN KEY (`refaccion_id`)
    REFERENCES `taller_jpa`.`refaccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`cliente` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`cliente` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono_movil` VARCHAR(10) NULL,
  `telefono_fijo` VARCHAR(10) NULL,
  `direccion` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`nota` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`nota` (
  `id` INT NOT NULL,
  `estado` ENUM('en proceso', 'finalizado') NULL,
  `fecha_registro` DATETIME NULL,
  `cliente_id` INT NOT NULL,
  `empleado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nota_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_nota_empleado1_idx` (`empleado_id` ASC) VISIBLE,
  CONSTRAINT `fk_nota_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `taller_jpa`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `taller_jpa`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`dispositivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`dispositivo` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`dispositivo` (
  `id` INT NOT NULL,
  `tipo_dispositivo` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `imei` VARCHAR(45) NULL,
  `utils` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `nota_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dispositivo_nota1_idx` (`nota_id` ASC) VISIBLE,
  CONSTRAINT `fk_dispositivo_nota1`
    FOREIGN KEY (`nota_id`)
    REFERENCES `taller_jpa`.`nota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`reparacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`reparacion` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`reparacion` (
  `id` INT NOT NULL,
  `tipo_reparacion` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` FLOAT NULL,
  `abono` FLOAT NULL,
  `dispositivo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reparacion_dispositivo1_idx` (`dispositivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_reparacion_dispositivo1`
    FOREIGN KEY (`dispositivo_id`)
    REFERENCES `taller_jpa`.`dispositivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`Venta` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`Venta` (
  `id` INT NOT NULL,
  `fecha` VARCHAR(45) NULL,
  `precioTotal` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `nota_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Venta_nota1_idx` (`nota_id` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_nota1`
    FOREIGN KEY (`nota_id`)
    REFERENCES `taller_jpa`.`nota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`DetalleVenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`DetalleVenta` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`DetalleVenta` (
  `id` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  `precioUnitario` VARCHAR(45) NULL,
  `precioVenta` VARCHAR(45) NULL,
  `precioTotal` VARCHAR(45) NULL,
  `Venta_id` INT NOT NULL,
  `refaccion_id` INT NOT NULL,
  `reparacion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DetalleVenta_Venta1_idx` (`Venta_id` ASC) VISIBLE,
  INDEX `fk_DetalleVenta_refaccion1_idx` (`refaccion_id` ASC) VISIBLE,
  INDEX `fk_DetalleVenta_reparacion1_idx` (`reparacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleVenta_Venta1`
    FOREIGN KEY (`Venta_id`)
    REFERENCES `taller_jpa`.`Venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleVenta_refaccion1`
    FOREIGN KEY (`refaccion_id`)
    REFERENCES `taller_jpa`.`refaccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleVenta_reparacion1`
    FOREIGN KEY (`reparacion_id`)
    REFERENCES `taller_jpa`.`reparacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`MetodoPago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`MetodoPago` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`MetodoPago` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`Pago` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`Pago` (
  `id` INT NOT NULL,
  `monto` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `MetodoPago_id` INT NOT NULL,
  `Venta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pago_MetodoPago1_idx` (`MetodoPago_id` ASC) VISIBLE,
  INDEX `fk_Pago_Venta1_idx` (`Venta_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pago_MetodoPago1`
    FOREIGN KEY (`MetodoPago_id`)
    REFERENCES `taller_jpa`.`MetodoPago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_Venta1`
    FOREIGN KEY (`Venta_id`)
    REFERENCES `taller_jpa`.`Venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into tipo_empleado(nombre) values ("Recepcionista"),("Técnico"),("Gerente");
select * from usuario;
select * from empleado;
select * from tipo_empleado;
