-- MySQL Script generated by MySQL Workbench
-- Mon May  5 11:52:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taller_jpa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `taller_jpa` ;

-- -----------------------------------------------------
-- Schema taller_jpa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taller_jpa` DEFAULT CHARACTER SET utf8 ;
USE `taller_jpa` ;

-- -----------------------------------------------------
-- Table `taller_jpa`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`direccion` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`direccion` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `colonia` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`tipo_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`tipo_empleado` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`tipo_empleado` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`empleado` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`empleado` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `correo` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NOT NULL,
  `rfc` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NOT NULL,
  `fecha_baja` DATETIME NOT NULL,
  `isActivo` TINYINT NOT NULL DEFAULT 1,
  `D_id` BIGINT NOT NULL,
  `TE_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_direccion1_idx` (`D_id` ASC) VISIBLE,
  INDEX `fk_empleado_tipo_empleado1_idx` (`TE_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_direccion1`
    FOREIGN KEY (`D_id`)
    REFERENCES `taller_jpa`.`direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_tipo_empleado1`
    FOREIGN KEY (`TE_id`)
    REFERENCES `taller_jpa`.`tipo_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `taller_jpa`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`usuario` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  `E_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_empleado1_idx` (`E_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empleado1`
    FOREIGN KEY (`E_id`)
    REFERENCES `taller_jpa`.`empleado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into tipo_empleado(nombre) values ("Recepcionista"),("Técnico"),("Gerente");
select * from usuario;
select * from empleado;
select * from tipo_empleado;
