-- MySQL Script generated by MySQL Workbench
-- Thu May 22 12:53:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taller_jpa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `taller_jpa` ;

-- -----------------------------------------------------
-- Schema taller_jpa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taller_jpa` DEFAULT CHARACTER SET utf8 ;
USE `taller_jpa` ;

-- -----------------------------------------------------
-- Table `taller_jpa`.`tipo_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`tipo_empleado` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`tipo_empleado` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`direccion` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`direccion` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `colonia` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`empleado` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`empleado` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `correo` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NOT NULL,
  `rfc` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NOT NULL,
  `fecha_baja` DATETIME NULL,
  `isActivo` TINYINT NOT NULL DEFAULT 1,
  `D_id` BIGINT NOT NULL,
  `TE_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_tipo_empleado1_idx` (`TE_id` ASC) VISIBLE,
  INDEX `fk_empleado_direccion1_idx` (`D_id` ASC) VISIBLE,
  UNIQUE INDEX `direccion_id_UNIQUE` (`D_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_tipo_empleado1`
    FOREIGN KEY (`TE_id`)
    REFERENCES `taller_jpa`.`tipo_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_direccion1`
    FOREIGN KEY (`D_id`)
    REFERENCES `taller_jpa`.`direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`usuario` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  `E_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_empleado1_idx` (`E_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empleado1`
    FOREIGN KEY (`E_id`)
    REFERENCES `taller_jpa`.`empleado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`cliente` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`cliente` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `telefono_movil` VARCHAR(12) NULL,
  `telefono_fijo` VARCHAR(12) NULL,
  `direccion` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `taller_jpa`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`proveedor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(12) NULL,
  `direccion` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `taller_jpa`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`categoria` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taller_jpa`.`refaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taller_jpa`.`refaccion` ;

CREATE TABLE IF NOT EXISTS `taller_jpa`.`refaccion` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(200) NULL,
  `stock` INT NULL DEFAULT 0,
  `precio_venta` FLOAT NULL,
  `precio_compra` FLOAT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `proveedor_id` BIGINT NOT NULL,
  `categoria_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_refaccion_proveedor_idx` (`proveedor_id` ASC) VISIBLE,
  INDEX `fk_refaccion_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_refaccion_proveedor`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `taller_jpa`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refaccion_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `taller_jpa`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into tipo_empleado(nombre) values ("Recepcionista"),("Técnico"),("Gerente");
insert into categoria(nombre) values ("Pantall"),("Bateria"),("Centro de Carga");
select * from usuario;
select * from empleado;
select * from tipo_empleado;
select * from cliente;
